import 'dart:ui';

class CompactTheme {
  final Brightness brightness;
  final Color buttonHovered,
      buttonDown,
      dangerButtonColor,
      cursorColor,
      dividerColor,
      searchBarColor,
      hoveredSurfaceColor,
      highlightedHoveredSurfaceColor,
      downSurfaceColor,
      focusedSurfaceColor,
      surfaceColor,
      backgroundColor,
      cardColor,
      labelColor,
      iconColor,
      breadcrumbSeparatorColor,
      primaryTextColor,
      secondaryTextColor,
      onSurfaceTextColor,
      selectedTextColor,
      selectedColor,
      selectedTreeColor,
      hoveredTreeColor,
      unfocusedSelectedTreeColor,
      hoveredSelectedTreeColor,
      tooltipBackgroundColor,
      tooltipPrimaryTextColor,
      tooltipSecondaryTextColor,
      tooltipBorderColor,
      progressBarTrackColor,
      progressBarValueColor,
      textSearchHighlightBackgroundColor,
      textSearchHighlightBorderColor,
      scrollbarThumbColor,
      tabViewGroupSectionHighlightColor,
      blueprintMinorGridColor,
      blueprintMajorGridColor,
      nodeBorderColor,
      selectedNodeBorderColor,
      executionColor,
      selectionColor,
      selectionBorderColor,
      nodeErrorColor,
      nodeWarningColor,
      nodeBubbleColor,
      nodeGroupBorderColor,
      nodeGroupSelectedBorderColor,
      nodeGroupTextColor;

  const CompactTheme.dark({
    this.brightness = Brightness.dark,
    this.buttonHovered = const Color(0x1affffff),
    this.buttonDown = const Color(0x26000000),
    this.dangerButtonColor = const Color(0xffd32f2f),
    this.cursorColor = const Color(0xffffffff),
    this.dividerColor = const Color(0xff323232),
    this.searchBarColor = const Color(0xff323232),
    this.hoveredSurfaceColor = const Color(0xff323232),
    this.highlightedHoveredSurfaceColor = const Color(0xff646464),
    this.downSurfaceColor = const Color(0xff282828),
    this.focusedSurfaceColor = const Color(0xff2e7da9),
    this.surfaceColor = const Color(0xff1e1e1e),
    this.backgroundColor = const Color(0xff141414),
    this.cardColor = const Color(0xff323232),
    this.labelColor = const Color(0xff787878),
    this.iconColor = const Color(0xffffffff),
    this.primaryTextColor = const Color(0xffc8c8c8),
    this.secondaryTextColor = const Color(0xff969696),
    this.onSurfaceTextColor = const Color(0xff1e1e1e),
    this.selectedTextColor = const Color(0xff141414),
    this.selectedColor = const Color(0xffffffff),
    this.unfocusedSelectedTreeColor = const Color(0xff0d202c),
    this.selectedTreeColor = const Color(0xff122936),
    this.hoveredTreeColor = const Color(0xff242424),
    this.hoveredSelectedTreeColor = const Color(0xff1a384b),
    this.tooltipBackgroundColor = const Color(0xff282828),
    this.tooltipPrimaryTextColor = const Color(0xffc8c8c8),
    this.tooltipSecondaryTextColor = const Color(0xff969696),
    this.tooltipBorderColor = const Color(0xff323232),
    this.progressBarTrackColor = const Color(0xff464646),
    this.progressBarValueColor = const Color(0xff2e7da9),
    this.textSearchHighlightBackgroundColor = const Color(0x32ffb84e),
    this.textSearchHighlightBorderColor = const Color(0x80da8710),
    this.scrollbarThumbColor = const Color(0x80646464),
    this.tabViewGroupSectionHighlightColor = const Color(0x80fafafa),
    this.breadcrumbSeparatorColor = const Color(0xff323232),
    this.blueprintMinorGridColor = const Color(0xff1c1c1c),
    this.blueprintMajorGridColor = const Color(0xff282828),
    this.nodeBorderColor = const Color(0xff020202),
    this.selectedNodeBorderColor = const Color(0xffffffff),
    this.executionColor = const Color(0xffffffff),
    this.selectionColor = const Color(0x672e7da9),
    this.selectionBorderColor = const Color(0xff2e7da9),
    this.nodeErrorColor = const Color(0xffd32f2f),
    this.nodeWarningColor = const Color(0xffffb74d),
    this.nodeBubbleColor = const Color(0xff2e7da9),
    this.nodeGroupBorderColor = const Color(0xff2e7da9),
    this.nodeGroupSelectedBorderColor = const Color(0xffffffff),
    this.nodeGroupTextColor = const Color(0xff1c1c1c),
  });

  const CompactTheme.light({
    this.brightness = Brightness.light,
    this.buttonHovered = const Color(0x1a000000),
    this.buttonDown = const Color(0x26000000),
    this.dangerButtonColor = const Color(0xffd32f2f),
    this.cursorColor = const Color(0xff000000),
    this.dividerColor = const Color(0xffe0e0e0),
    this.searchBarColor = const Color(0xffe0e0e0),
    this.hoveredSurfaceColor = const Color(0xffe0e0e0),
    this.highlightedHoveredSurfaceColor = const Color(0xffafafaf),
    this.downSurfaceColor = const Color(0xffbebebe),
    this.focusedSurfaceColor = const Color(0xff5daad0),
    this.surfaceColor = const Color(0xffffffff),
    this.backgroundColor = const Color(0xffbebebe),
    this.cardColor = const Color(0xffffffff),
    this.labelColor = const Color(0xff787878),
    this.iconColor = const Color(0xff000000),
    this.primaryTextColor = const Color(0xff101010),
    this.secondaryTextColor = const Color(0xff969696),
    this.onSurfaceTextColor = const Color(0xffffffff),
    this.selectedTextColor = const Color(0xffffffff),
    this.selectedColor = const Color(0xff000000),
    this.selectedTreeColor = const Color(0xffe6e6e6),
    this.hoveredTreeColor = const Color(0xffe0e0e0),
    this.unfocusedSelectedTreeColor = const Color(0xffe0e0e0),
    this.hoveredSelectedTreeColor = const Color(0xffd6d6d6),
    this.tooltipBackgroundColor = const Color(0xffe0e0e0),
    this.tooltipPrimaryTextColor = const Color(0xff000000),
    this.tooltipSecondaryTextColor = const Color(0xff969696),
    this.tooltipBorderColor = const Color(0xff969696),
    this.progressBarTrackColor = const Color(0xffc9c9c9),
    this.progressBarValueColor = const Color(0xff5daad0),
    this.textSearchHighlightBackgroundColor = const Color(0x80ffb84e),
    this.textSearchHighlightBorderColor = const Color(0xffda8710),
    this.scrollbarThumbColor = const Color(0x80e0e0e0),
    this.tabViewGroupSectionHighlightColor = const Color(0x80fafafa),
    this.breadcrumbSeparatorColor = const Color(0xffe0e0e0),
    this.blueprintMinorGridColor = const Color(0xffd3d3d3),
    this.blueprintMajorGridColor = const Color(0xffafafaf),
    this.nodeBorderColor = const Color(0xffafafaf),
    this.selectedNodeBorderColor = const Color(0xff5b5b5b),
    this.executionColor = const Color(0xff5b5b5b),
    this.selectionColor = const Color(0x672e7da9),
    this.selectionBorderColor = const Color(0xff2e7da9),
    this.nodeErrorColor = const Color(0xffd32f2f),
    this.nodeWarningColor = const Color(0xffffb74d),
    this.nodeBubbleColor = const Color(0xff5daad0),
    this.nodeGroupBorderColor = const Color(0xff5daad0),
    this.nodeGroupSelectedBorderColor = const Color(0xff5b5b5b),
    this.nodeGroupTextColor = const Color(0xffbbbbbb),
  });
}
